### ISSUE TITLE
Order of the address books on Mobile vs on Desktop are different. 

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-contacts#45] opened 2020-08-28 09:20 UTC
**Actual Result**

Address books order on the mobile and desktop are different.

On Desktop:
![image](https://user-images.githubusercontent.com/69950655/91542718-75b5fe80-e948-11ea-8ebe-e96cf5d41714.png)

On Mobile:
![mobile](https://user-images.githubusercontent.com/69950655/91543486-bd3c8a80-e948-11ea-829f-9154bba442f7.PNG)

**Expected result**

On the mobile and on the desktop, address book order should be consistent.

**Environment**
- Desktop: Chrome Ubuntu
- Mobile: iphone 7

**Comment by huy-ta** [comment] 2020-09-17 10:15
I cannot reproduce the issue anymore. I'll close the issue for now. Can you confirm and reopen the issue if it still persists? @tlle14

**Comment by tlle14** [comment] 2020-09-17 10:59
The issue is no longer existing. 

Thank @huy-ta

**Closed** 2020-09-17 10:58 UTC
Labels: Minor, bug, irreproducible
